[project]
name = "pyarinc424"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
    "psycopg2-binary>=2.9.10",
    "rich>=14.0.0",
]

[dependency-groups]
dev = [
        "pytest>=7.0.0",
        "pytest-cov>=4.0.0",
    ]

[tool.pytest.ini_options]
pythonpath = [
  "src"
]