# Store of mappings of each ARINC-424 record in FAA CIFP output.

record_maps = [
    {
        "name": "airport",
        "section_code": "P",
        "subsection_code": "A",
        "section_pos": 4,
        "subsection_pos": 12,
        "cont_rec_pos": 21,
        "cont_rec_vals": [0, 1],
        "columns": [
            {"id": 1, "start": 0, "end": 1, "name": "ST"},
            {"id": 2, "start": 1, "end": 4, "name": "Cust_Area"},
            {"id": 3, "start": 4, "end": 5, "name": "SecCode"},
            {"id": 4, "start": 6, "end": 10, "name": "ArptIdent"},
            {"id": 5, "start": 10, "end": 12, "name": "ICAOCode"},
            {"id": 6, "start": 12, "end": 13, "name": "SubCode"},
            {"id": 7, "start": 13, "end": 16, "name": "AtaIata"},
            {"id": 8, "start": 21, "end": 22, "name": "ContRecordNumber"},
            {"id": 9, "start": 22, "end": 27, "name": "SpeedLimitAlt"},
            {"id": 10, "start": 27, "end": 30, "name": "LongestRunway"},
            {"id": 11, "start": 30, "end": 31, "name": "IFR"},
            {"id": 12, "start": 31, "end": 32, "name": "LongRunway"},
            {"id": 13, "start": 32, "end": 41, "name": "Latitude"},
            {"id": 14, "start": 41, "end": 51, "name": "Longitude"},
            {"id": 15, "start": 51, "end": 56, "name": "MagVar"},
            {"id": 16, "start": 56, "end": 61, "name": "Elev"},
            {"id": 17, "start": 61, "end": 64, "name": "SpeedLimit"},
            {"id": 18, "start": 64, "end": 68, "name": "RecdVHF"},
            {"id": 19, "start": 68, "end": 70, "name": "ICAOCode2"},
            {"id": 20, "start": 70, "end": 75, "name": "TransAltitude"},
            {"id": 21, "start": 75, "end": 80, "name": "TransLevel"},
            {"id": 22, "start": 80, "end": 81, "name": "Pub_Mil"},
            {"id": 23, "start": 81, "end": 84, "name": "TimeZone"},
            {"id": 24, "start": 84, "end": 85, "name": "DayTime"},
            {"id": 25, "start": 85, "end": 86, "name": "MT_Ind"},
            {"id": 26, "start": 86, "end": 89, "name": "DatumCode"},
            {"id": 27, "start": 93, "end": 123, "name": "AirportName"},
            {"id": 28, "start": 123, "end": 128, "name": "FileRecordNumber"},
            {"id": 29, "start": 128, "end": 132, "name": "Cycle"},
        ],
    },
    {
        "name": "heliport",
        "section_code": "H",
        "subsection_code": "A",
        "section_pos": 4,
        "subsection_pos": 12,
        "cont_rec_pos": 21,
        "cont_rec_vals": [0, 1],
        "columns": [
            {"id": 1, "start": 0, "end": 1, "name": "ST"},
            {"id": 2, "start": 1, "end": 4, "name": "Cust_Area"},
            {"id": 3, "start": 4, "end": 5, "name": "SecCode"},
            {"id": 4, "start": 6, "end": 10, "name": "Heliport_Ident"},
            {"id": 5, "start": 10, "end": 12, "name": "ICAOCode"},
            {"id": 6, "start": 12, "end": 13, "name": "SubCode"},
            {"id": 7, "start": 13, "end": 16, "name": "AtaIata"},
            {"id": 8, "start": 16, "end": 21, "name": "Pad_Ident"},
            {"id": 9, "start": 21, "end": 22, "name": "ContRecordNumber"},
            {"id": 10, "start": 22, "end": 27, "name": "SpeedLimitAlt"},
            {"id": 11, "start": 27, "end": 30, "name": "Datum_Code"},
            {"id": 12, "start": 30, "end": 31, "name": "IFR"},
            {"id": 13, "start": 32, "end": 41, "name": "Latitude"},
            {"id": 14, "start": 41, "end": 51, "name": "Longitude"},
            {"id": 15, "start": 51, "end": 56, "name": "MagVar"},
            {"id": 16, "start": 56, "end": 61, "name": "Elev"},
            {"id": 17, "start": 61, "end": 64, "name": "SpeedLimit"},
            {"id": 18, "start": 64, "end": 68, "name": "RecdVHF"},
            {"id": 19, "start": 68, "end": 70, "name": "ICAOCode2"},
            {"id": 20, "start": 70, "end": 75, "name": "TransAltitude"},
            {"id": 21, "start": 75, "end": 80, "name": "TransLevel"},
            {"id": 22, "start": 80, "end": 81, "name": "Pub_Mil"},
            {"id": 23, "start": 81, "end": 84, "name": "TimeZone"},
            {"id": 24, "start": 84, "end": 85, "name": "DayTime"},
            {"id": 25, "start": 85, "end": 91, "name": "Pad_Dimensions"},
            {"id": 26, "start": 91, "end": 92, "name": "MT_Ind"},
            {"id": 27, "start": 93, "end": 123, "name": "Heliport_Name"},
            {"id": 28, "start": 123, "end": 128, "name": "FileRecordNumber"},
            {"id": 29, "start": 128, "end": 132, "name": "Cycle"},
        ],
    },
    {
        "name": "enroute_waypoint",
        "section_code": "E",
        "subsection_code": "A",
        "section_pos": 4,
        "subsection_pos": 5,
        "cont_rec_pos": 21,
        "cont_rec_vals": [0, 1],
        "columns": [
            {"id": 1, "start": 0, "end": 1, "name": "ST"},
            {"id": 2, "start": 1, "end": 4, "name": "Cust_Area"},
            {"id": 3, "start": 4, "end": 5, "name": "SecCode"},
            {"id": 4, "start": 5, "end": 6, "name": "SubCode"},
            {"id": 5, "start": 6, "end": 10, "name": "Regn_ArptCode"},
            {"id": 6, "start": 10, "end": 12, "name": "IcaoCode"},
            {"id": 7, "start": 12, "end": 13, "name": "SubCode2"},
            {"id": 8, "start": 13, "end": 18, "name": "WaypointIdent"},
            {"id": 9, "start": 19, "end": 21, "name": "IcaoCode2"},
            {"id": 10, "start": 21, "end": 22, "name": "ContRecordNumber"},
            {"id": 11, "start": 26, "end": 29, "name": "Type"},
            {"id": 12, "start": 29, "end": 31, "name": "Usage"},
            {"id": 13, "start": 32, "end": 41, "name": "Latitude"},
            {"id": 14, "start": 41, "end": 51, "name": "Longitude"},
            {"id": 15, "start": 74, "end": 79, "name": "DMagVar"},
            {"id": 16, "start": 79, "end": 84, "name": "WPElev"},
            {"id": 17, "start": 84, "end": 87, "name": "DatumCode"},
            {"id": 18, "start": 95, "end": 98, "name": "NameInd"},
            {"id": 19, "start": 98, "end": 123, "name": "Name_Desc"},
            {"id": 20, "start": 123, "end": 128, "name": "FileRecordNumber"},
            {"id": 21, "start": 128, "end": 132, "name": "Cycle"},
        ],
    },
        {
        "name": "terminal_waypoint",
        "section_code": "P",
        "subsection_code": "C",
        "section_pos": 4,
        "subsection_pos": 12,
        "cont_rec_pos": 21,
        "cont_rec_vals": [0, 1],
        "columns": [
            {"id": 1, "start": 0, "end": 1, "name": "ST"},
            {"id": 2, "start": 1, "end": 4, "name": "Cust_Area"},
            {"id": 3, "start": 4, "end": 5, "name": "SecCode"},
            {"id": 4, "start": 6, "end": 10, "name": "Airport_Ident"},
            {"id": 5, "start": 10, "end": 12, "name": "IcaoCode"},
            {"id": 6, "start": 12, "end": 13, "name": "SubCode"},
            {"id": 7, "start": 13, "end": 18, "name": "WaypointIdent"},
            {"id": 8, "start": 19, "end": 21, "name": "IcaoCode2"},
            {"id": 9, "start": 21, "end": 22, "name": "ContRecordNumber"},
            {"id": 11, "start": 26, "end": 29, "name": "Type"},
            {"id": 12, "start": 29, "end": 31, "name": "Usage"},
            {"id": 13, "start": 32, "end": 41, "name": "Latitude"},
            {"id": 14, "start": 41, "end": 51, "name": "Longitude"},
            {"id": 15, "start": 74, "end": 79, "name": "DMagVar"},
            {"id": 16, "start": 79, "end": 84, "name": "WPElev"},
            {"id": 17, "start": 84, "end": 87, "name": "DatumCode"},
            {"id": 18, "start": 95, "end": 98, "name": "NameInd"},
            {"id": 19, "start": 98, "end": 123, "name": "Name_Desc"},
            {"id": 20, "start": 123, "end": 128, "name": "FileRecordNumber"},
            {"id": 21, "start": 128, "end": 132, "name": "Cycle"},
        ],
    },
            {
        "name": "heli_terminal_waypoint",
        "section_code": "H",
        "subsection_code": "C",
        "section_pos": 4,
        "subsection_pos": 12,
        "cont_rec_pos": 21,
        "cont_rec_vals": [0, 1],
        "columns": [
            {"id": 1, "start": 0, "end": 1, "name": "ST"},
            {"id": 2, "start": 1, "end": 4, "name": "Cust_Area"},
            {"id": 3, "start": 4, "end": 5, "name": "SecCode"},
            {"id": 4, "start": 6, "end": 10, "name": "Heliport_Ident"},
            {"id": 5, "start": 10, "end": 12, "name": "IcaoCode"},
            {"id": 6, "start": 12, "end": 13, "name": "SubCode"},
            {"id": 7, "start": 13, "end": 18, "name": "WaypointIdent"},
            {"id": 8, "start": 19, "end": 21, "name": "IcaoCode2"},
            {"id": 9, "start": 21, "end": 22, "name": "ContRecordNumber"},
            {"id": 11, "start": 26, "end": 29, "name": "Type"},
            {"id": 12, "start": 29, "end": 31, "name": "Usage"},
            {"id": 13, "start": 32, "end": 41, "name": "Latitude"},
            {"id": 14, "start": 41, "end": 51, "name": "Longitude"},
            {"id": 15, "start": 74, "end": 79, "name": "DMagVar"},
            {"id": 16, "start": 79, "end": 84, "name": "WPElev"},
            {"id": 17, "start": 84, "end": 87, "name": "DatumCode"},
            {"id": 18, "start": 95, "end": 98, "name": "NameInd"},
            {"id": 19, "start": 98, "end": 123, "name": "Name_Desc"},
            {"id": 20, "start": 123, "end": 128, "name": "FileRecordNumber"},
            {"id": 21, "start": 128, "end": 132, "name": "Cycle"},
        ],
    },
    {
        "name": "sid",
        "section_code": "P",
        "subsection_code": "D",
        "section_pos": 4,
        "subsection_pos": 12,
        "cont_rec_pos": 38,
        "cont_rec_vals": [0, 1],
        "columns": [
            {"id": 1, "start": 0, "end": 1, "name": "ST"},
            {"id": 2, "start": 1, "end": 4, "name": "Cust_Area"},
            {"id": 3, "start": 4, "end": 5, "name": "SecCode"},
            {"id": 4, "start": 6, "end": 10, "name": "ArptIdent"},
            {"id": 5, "start": 10, "end": 12, "name": "ICAOCode"},
            {"id": 6, "start": 12, "end": 13, "name": "SubCode"},
            {"id": 7, "start": 13, "end": 19, "name": "ProcIdent"},
            {"id": 8, "start": 19, "end": 20, "name": "RouteType"},
            {"id": 9, "start": 20, "end": 25, "name": "TransIdent"},
            {"id": 10, "start": 26, "end": 29, "name": "SeqNbr"},
            {"id": 11, "start": 29, "end": 34, "name": "FixIdent"},
            {"id": 12, "start": 34, "end": 36, "name": "ICAOCode2"},
            {"id": 13, "start": 36, "end": 37, "name": "SecCode2"},
            {"id": 14, "start": 37, "end": 38, "name": "SubCode2"},
            {"id": 15, "start": 38, "end": 39, "name": "ContRecordNumber"},
            {"id": 16, "start": 39, "end": 43, "name": "DescCode"},
            {"id": 17, "start": 43, "end": 44, "name": "TurnDir"},
            {"id": 18, "start": 44, "end": 47, "name": "RNP"},
            {"id": 19, "start": 47, "end": 49, "name": "PathTerminator"},
            {"id": 20, "start": 49, "end": 50, "name": "TurnDirValid"},
            {"id": 21, "start": 50, "end": 54, "name": "RecdNavaid"},
            {"id": 22, "start": 54, "end": 56, "name": "ICAOCode3"},
            {"id": 23, "start": 56, "end": 62, "name": "ArcRadius"},
            {"id": 24, "start": 62, "end": 66, "name": "Theta"},
            {"id": 25, "start": 66, "end": 70, "name": "Rho"},
            {"id": 26, "start": 70, "end": 74, "name": "MagCrs"},
            {"id": 27, "start": 74, "end": 78, "name": "RtHoldDistTime"},
            {"id": 28, "start": 78, "end": 79, "name": "SecCode3"},
            {"id": 29, "start": 79, "end": 80, "name": "SubCode3"},
            {"id": 30, "start": 82, "end": 83, "name": "AltDesc"},
            {"id": 31, "start": 83, "end": 84, "name": "ATC"},
            {"id": 32, "start": 84, "end": 89, "name": "Altitude1"},
            {"id": 33, "start": 89, "end": 94, "name": "Altitude2"},
            {"id": 34, "start": 94, "end": 99, "name": "TransAltitude"},
            {"id": 35, "start": 99, "end": 102, "name": "SpeedLimit"},
            {"id": 36, "start": 102, "end": 106, "name": "VertAngle"},
            {"id": 37, "start": 106, "end": 111, "name": "CenterFix"},
            {"id": 38, "start": 111, "end": 112, "name": "MultiCode"},
            {"id": 39, "start": 112, "end": 114, "name": "ICAOCode4"},
            {"id": 40, "start": 114, "end": 115, "name": "SecCode4"},
            {"id": 41, "start": 115, "end": 116, "name": "SubCode4"},
            {"id": 42, "start": 116, "end": 117, "name": "GNSS_FMSInd"},
            {"id": 43, "start": 117, "end": 118, "name": "SpeedLimitInd"},
            {"id": 44, "start": 118, "end": 119, "name": "RouteQual1"},
            {"id": 45, "start": 119, "end": 120, "name": "RouteQual2"},
            {"id": 46, "start": 123, "end": 128, "name": "FileRecordNumber"},
            {"id": 47, "start": 128, "end": 132, "name": "Cycle"},
        ],
    },
    {
        "name": "star",
        "section_code": "P",
        "subsection_code": "E",
        "section_pos": 4,
        "subsection_pos": 12,
        "cont_rec_pos": 38,
        "cont_rec_vals": [0, 1],
        "columns": [
            {"id": 1, "start": 0, "end": 1, "name": "ST"},
            {"id": 2, "start": 1, "end": 4, "name": "Cust_Area"},
            {"id": 3, "start": 4, "end": 5, "name": "SecCode"},
            {"id": 4, "start": 6, "end": 10, "name": "ArptIdent"},
            {"id": 5, "start": 10, "end": 12, "name": "ICAOCode"},
            {"id": 6, "start": 12, "end": 13, "name": "SubCode"},
            {"id": 7, "start": 13, "end": 19, "name": "ProcIdent"},
            {"id": 8, "start": 19, "end": 20, "name": "RouteType"},
            {"id": 9, "start": 20, "end": 25, "name": "TransIdent"},
            {"id": 10, "start": 26, "end": 29, "name": "SeqNbr"},
            {"id": 11, "start": 29, "end": 34, "name": "FixIdent"},
            {"id": 12, "start": 34, "end": 36, "name": "ICAOCode2"},
            {"id": 13, "start": 36, "end": 37, "name": "SecCode2"},
            {"id": 14, "start": 37, "end": 38, "name": "SubCode2"},
            {"id": 15, "start": 38, "end": 39, "name": "ContRecordNumber"},
            {"id": 16, "start": 39, "end": 43, "name": "DescCode"},
            {"id": 17, "start": 43, "end": 44, "name": "TurnDir"},
            {"id": 18, "start": 44, "end": 47, "name": "RNP"},
            {"id": 19, "start": 47, "end": 49, "name": "PathTerminator"},
            {"id": 20, "start": 49, "end": 50, "name": "TurnDirValid"},
            {"id": 21, "start": 50, "end": 54, "name": "RecdNavaid"},
            {"id": 22, "start": 54, "end": 56, "name": "ICAOCode3"},
            {"id": 23, "start": 56, "end": 62, "name": "ArcRadius"},
            {"id": 24, "start": 62, "end": 66, "name": "Theta"},
            {"id": 25, "start": 66, "end": 70, "name": "Rho"},
            {"id": 26, "start": 70, "end": 74, "name": "MagCrs"},
            {"id": 27, "start": 74, "end": 78, "name": "RtHoldDistTime"},
            {"id": 28, "start": 78, "end": 79, "name": "SecCode3"},
            {"id": 29, "start": 79, "end": 80, "name": "SubCode3"},
            {"id": 30, "start": 82, "end": 83, "name": "AltDesc"},
            {"id": 31, "start": 83, "end": 84, "name": "ATC"},
            {"id": 32, "start": 84, "end": 89, "name": "Altitude1"},
            {"id": 33, "start": 89, "end": 94, "name": "Altitude2"},
            {"id": 34, "start": 94, "end": 99, "name": "TransAltitude"},
            {"id": 35, "start": 99, "end": 102, "name": "SpeedLimit"},
            {"id": 36, "start": 102, "end": 106, "name": "VertAngle"},
            {"id": 37, "start": 106, "end": 111, "name": "CenterFix"},
            {"id": 38, "start": 111, "end": 112, "name": "MultiCode"},
            {"id": 39, "start": 112, "end": 114, "name": "ICAOCode4"},
            {"id": 40, "start": 114, "end": 115, "name": "SecCode4"},
            {"id": 41, "start": 115, "end": 116, "name": "SubCode4"},
            {"id": 42, "start": 116, "end": 117, "name": "GNSS_FMSInd"},
            {"id": 43, "start": 117, "end": 118, "name": "SpeedLimitInd"},
            {"id": 44, "start": 118, "end": 119, "name": "RouteQual1"},
            {"id": 45, "start": 119, "end": 120, "name": "RouteQual2"},
            {"id": 46, "start": 123, "end": 128, "name": "FileRecordNumber"},
            {"id": 47, "start": 128, "end": 132, "name": "Cycle"},
        ],
    },
    {
        "name": "approach",
        "section_code": "P",
        "subsection_code": "F",
        "section_pos": 4,
        "subsection_pos": 12,
        "cont_rec_pos": 38,
        "cont_rec_vals": [0, 1],
        "columns": [
            {"id": 1, "start": 0, "end": 1, "name": "ST"},
            {"id": 2, "start": 1, "end": 4, "name": "Cust_Area"},
            {"id": 3, "start": 4, "end": 5, "name": "SecCode"},
            {"id": 4, "start": 6, "end": 10, "name": "ArptIdent"},
            {"id": 5, "start": 10, "end": 12, "name": "ICAOCode"},
            {"id": 6, "start": 12, "end": 13, "name": "SubCode"},
            {"id": 7, "start": 13, "end": 19, "name": "ProcIdent"},
            {"id": 8, "start": 19, "end": 20, "name": "RouteType"},
            {"id": 9, "start": 20, "end": 25, "name": "TransIdent"},
            {"id": 10, "start": 26, "end": 29, "name": "SeqNbr"},
            {"id": 11, "start": 29, "end": 34, "name": "FixIdent"},
            {"id": 12, "start": 34, "end": 36, "name": "ICAOCode2"},
            {"id": 13, "start": 36, "end": 37, "name": "SecCode2"},
            {"id": 14, "start": 37, "end": 38, "name": "SubCode2"},
            {"id": 15, "start": 38, "end": 39, "name": "ContRecordNumber"},
            {"id": 16, "start": 39, "end": 43, "name": "DescCode"},
            {"id": 17, "start": 43, "end": 44, "name": "TurnDir"},
            {"id": 18, "start": 44, "end": 47, "name": "RNP"},
            {"id": 19, "start": 47, "end": 49, "name": "PathTerminator"},
            {"id": 20, "start": 49, "end": 50, "name": "TurnDirValid"},
            {"id": 21, "start": 50, "end": 54, "name": "RecdNavaid"},
            {"id": 22, "start": 54, "end": 56, "name": "ICAOCode3"},
            {"id": 23, "start": 56, "end": 62, "name": "ArcRadius"},
            {"id": 24, "start": 62, "end": 66, "name": "Theta"},
            {"id": 25, "start": 66, "end": 70, "name": "Rho"},
            {"id": 26, "start": 70, "end": 74, "name": "MagCrs"},
            {"id": 27, "start": 74, "end": 78, "name": "RtHoldDistTime"},
            {"id": 28, "start": 78, "end": 79, "name": "SecCode3"},
            {"id": 29, "start": 79, "end": 80, "name": "SubCode3"},
            {"id": 30, "start": 82, "end": 83, "name": "AltDesc"},
            {"id": 31, "start": 83, "end": 84, "name": "ATC"},
            {"id": 32, "start": 84, "end": 89, "name": "Altitude1"},
            {"id": 33, "start": 89, "end": 94, "name": "Altitude2"},
            {"id": 34, "start": 94, "end": 99, "name": "TransAltitude"},
            {"id": 35, "start": 99, "end": 102, "name": "SpeedLimit"},
            {"id": 36, "start": 102, "end": 106, "name": "VertAngle"},
            {"id": 37, "start": 106, "end": 111, "name": "CenterFix"},
            {"id": 38, "start": 111, "end": 112, "name": "MultiCode"},
            {"id": 39, "start": 112, "end": 114, "name": "ICAOCode4"},
            {"id": 40, "start": 114, "end": 115, "name": "SecCode4"},
            {"id": 41, "start": 115, "end": 116, "name": "SubCode4"},
            {"id": 42, "start": 116, "end": 117, "name": "GNSS_FMSInd"},
            {"id": 43, "start": 117, "end": 118, "name": "SpeedLimitInd"},
            {"id": 44, "start": 118, "end": 119, "name": "RouteQual1"},
            {"id": 45, "start": 119, "end": 120, "name": "RouteQual2"},
            {"id": 46, "start": 123, "end": 128, "name": "FileRecordNumber"},
            {"id": 47, "start": 128, "end": 132, "name": "Cycle"},
        ],
    },
    {
        "name": "approach_cont",
        "section_code": "P",
        "subsection_code": "F",
        "section_pos": 4,
        "subsection_pos": 12,
        "cont_rec_pos": 38,
        "cont_rec_vals": [2],
        "columns": [
            {"id": 1, "start": 0, "end": 1, "name": "ST"},
            {"id": 2, "start": 1, "end": 4, "name": "Cust_Area"},
            {"id": 3, "start": 4, "end": 5, "name": "SecCode"},
            {"id": 4, "start": 6, "end": 10, "name": "ArptIdent"},
            {"id": 5, "start": 10, "end": 12, "name": "ICAOCode"},
            {"id": 6, "start": 12, "end": 13, "name": "SubCode"},
            {"id": 7, "start": 13, "end": 19, "name": "ProcIdent"},
            {"id": 8, "start": 19, "end": 20, "name": "RouteType"},
            {"id": 9, "start": 20, "end": 25, "name": "TransIdent"},
            {"id": 10, "start": 26, "end": 29, "name": "SeqNbr"},
            {"id": 11, "start": 29, "end": 34, "name": "FixIdent"},
            {"id": 12, "start": 34, "end": 36, "name": "ICAOCode2"},
            {"id": 13, "start": 36, "end": 37, "name": "SecCode2"},
            {"id": 14, "start": 37, "end": 38, "name": "SubCode2"},
            {"id": 15, "start": 38, "end": 39, "name": "ContRecordNumber"},
            {"id": 16, "start": 39, "end": 40, "name": "Appl_Type"},
            {"id": 17, "start": 40, "end": 41, "name": "FAS_Block"},
            {"id": 18, "start": 41, "end": 51, "name": "FAS_Block_LOS_Name"},
            {"id": 19, "start": 51, "end": 52, "name": "LNAV_VNAV"},
            {"id": 20, "start": 52, "end": 62, "name": "LNAV_VNAV_LOS_Name"},
            {"id": 21, "start": 62, "end": 63, "name": "LNAV"},
            {"id": 22, "start": 63, "end": 73, "name": "LNAV_LOS_Name"},
            {"id": 23, "start": 118, "end": 119, "name": "Route_Qual1"},
            {"id": 24, "start": 119, "end": 120, "name": "Route_Qual2"},
            {"id": 25, "start": 123, "end": 128, "name": "FileRecordNumber"},
            {"id": 26, "start": 128, "end": 132, "name": "Cycle"},
        ],
    },
    {
        "name": "runway",
        "section_code": "P",
        "subsection_code": "G",
        "section_pos": 4,
        "subsection_pos": 12,
        "cont_rec_pos": 21,
        "cont_rec_vals": [0, 1],
        "columns": [
            {"id": 1, "start": 0, "end": 1, "name": "ST"},
            {"id": 2, "start": 1, "end": 4, "name": "Cust_Area"},
            {"id": 3, "start": 4, "end": 5, "name": "Section_Code"},
            {"id": 4, "start": 6, "end": 10, "name": "Airport_Ident"},
            {"id": 5, "start": 10, "end": 12, "name": "ICAO_Code"},
            {"id": 6, "start": 12, "end": 13, "name": "Subsection_Code"},
            {"id": 7, "start": 13, "end": 18, "name": "Runway_Ident"},
            {"id": 8, "start": 21, "end": 22, "name": "Continuation_Record_Number"},
            {"id": 9, "start": 22, "end": 27, "name": "Runway_Length"},
            {"id": 10, "start": 27, "end": 31, "name": "Runway_Bearing"},
            {"id": 11, "start": 32, "end": 41, "name": "Latitude"},
            {"id": 12, "start": 41, "end": 51, "name": "Longitude"},
            {"id": 13, "start": 51, "end": 56, "name": "Runway_Gradient"},
            {"id": 14, "start": 60, "end": 66, "name": "LTP_Elipsoid_Height"},
            {"id": 15, "start": 66, "end": 71, "name": "Landing_Threshold_Elevation"},
            {"id": 16, "start": 71, "end": 75, "name": "Displaced_Theshold"},
            {"id": 17, "start": 75, "end": 77, "name": "TCH"},
            {"id": 18, "start": 77, "end": 80, "name": "Width"},
            {"id": 19, "start": 80, "end": 81, "name": "TCH_Value_Indicator"},
            {"id": 20, "start": 81, "end": 85, "name": "LOC_MLS_GLS_Ident"},
            {"id": 21, "start": 85, "end": 86, "name": "Category_Class"},
            {"id": 22, "start": 86, "end": 90, "name": "Stopway"},
            {"id": 23, "start": 90, "end": 94, "name": "Secondary_LOC_MLS_GLS_Ident"},
            {"id": 24, "start": 94, "end": 95, "name": "Category_Class_2"},
            {"id": 25, "start": 101, "end": 123, "name": "Runway_Description"},
            {"id": 26, "start": 123, "end": 128, "name": "File_Record_Number"},
            {"id": 27, "start": 128, "end": 132, "name": "Cycle"},
        ],
    },
    {
        "name": "pathpoint",
        "section_code": "P",
        "subsection_code": "P",
        "section_pos": 4,
        "subsection_pos": 12,
        "cont_rec_pos": 26,
        "cont_rec_vals": [0, 1],
        "columns": [
            {"id": 1, "start": 0, "end": 1, "name": "ST"},
            {"id": 2, "start": 1, "end": 4, "name": "Cust_Area"},
            {"id": 3, "start": 4, "end": 5, "name": "Section_Code"},
            {"id": 4, "start": 6, "end": 10, "name": "Airport_Ident"},
            {"id": 5, "start": 10, "end": 12, "name": "ICAO_Code"},
            {"id": 6, "start": 12, "end": 13, "name": "Subsection_Code"},
            {"id": 7, "start": 13, "end": 19, "name": "Approach_Ident"},
            {"id": 8, "start": 19, "end": 24, "name": "Runway_or_Helipad_Ident"},
            {"id": 9, "start": 24, "end": 26, "name": "Ops_Type"},
            {"id": 10, "start": 26, "end": 27, "name": "Continuation_Record_Number"},
            {"id": 11, "start": 27, "end": 28, "name": "Route_Indicator"},
            {"id": 12, "start": 28, "end": 30, "name": "SBAS_Service_Provider"},
            {"id": 13, "start": 30, "end": 32, "name": "Ref_Path_Data_Selector"},
            {"id": 14, "start": 32, "end": 36, "name": "Ref_Path_Data_Identifier"},
            {"id": 15, "start": 36, "end": 37, "name": "Approach_Perf_Designator"},
            {"id": 16, "start": 37, "end": 48, "name": "LTP_Latitude"},
            {"id": 17, "start": 48, "end": 60, "name": "LTP_Longitude"},
            {"id": 18, "start": 60, "end": 66, "name": "LTP_Ellipsoid_Height"},
            {"id": 19, "start": 66, "end": 70, "name": "GPA"},
            {"id": 20, "start": 70, "end": 81, "name": "FPAP_Latitude"},
            {"id": 21, "start": 81, "end": 93, "name": "FPAP_Longitude"},
            {"id": 22, "start": 93, "end": 98, "name": "Course_Width_at_Threshold"},
            {"id": 23, "start": 98, "end": 102, "name": "Length_Offset"},
            {"id": 24, "start": 102, "end": 108, "name": "TCH"},
            {"id": 25, "start": 108, "end": 109, "name": "TCH_Units_Selector"},
            {"id": 26, "start": 109, "end": 112, "name": "HAL"},
            {"id": 27, "start": 112, "end": 115, "name": "VAL"},
            {"id": 28, "start": 115, "end": 123, "name": "CRC_Remainder"},
            {"id": 29, "start": 123, "end": 128, "name": "File_Record_Number"},
            {"id": 30, "start": 128, "end": 132, "name": "Cycle"},
        ],
    },
    {
        "name": "pathpoint_cont",
        "section_code": "P",
        "subsection_code": "P",
        "section_pos": 4,
        "subsection_pos": 12,
        "cont_rec_pos": 26,
        "cont_rec_vals": [2],
        "columns": [
            {"id": 1, "start": 0, "end": 1, "name": "ST"},
            {"id": 2, "start": 1, "end": 4, "name": "Cust_Area"},
            {"id": 3, "start": 4, "end": 5, "name": "Section_Code"},
            {"id": 4, "start": 6, "end": 10, "name": "Airport_Ident"},
            {"id": 5, "start": 10, "end": 12, "name": "ICAO_Code"},
            {"id": 6, "start": 12, "end": 13, "name": "Subsection_Code"},
            {"id": 7, "start": 13, "end": 19, "name": "Approach_Ident"},
            {"id": 8, "start": 19, "end": 24, "name": "Runway_or_Helipad_Ident"},
            {"id": 9, "start": 24, "end": 26, "name": "Ops_Type"},
            {"id": 10, "start": 26, "end": 27, "name": "Continuation_Record_Number"},
            {"id": 11, "start": 27, "end": 28, "name": "Appl_Type"},
            {"id": 12, "start": 28, "end": 34, "name": "FPAP_Ellipsoid_Height"},
            {"id": 13, "start": 34, "end": 40, "name": "FPAP_Ortho_Height"},
            {"id": 14, "start": 40, "end": 46, "name": "LTP_Ortho_Height"},
            {"id": 15, "start": 46, "end": 56, "name": "Approach_Type_Ident"},
            {"id": 16, "start": 56, "end": 61, "name": "GNSS_Channel_No"},
            {"id": 17, "start": 71, "end": 74, "name": "HPC"},
            {"id": 18, "start": 74, "end": 123, "name": "Reserved"},
            {"id": 19, "start": 123, "end": 128, "name": "FileRecordNumber"},
            {"id": 20, "start": 128, "end": 132, "name": "Cycle"},
        ],
    },
    {
        "name": "heli_approach",
        "section_code": "H",
        "subsection_code": "F",
        "section_pos": 4,
        "subsection_pos": 12,
        "cont_rec_pos": 38,
        "cont_rec_vals": [0, 1],
        "columns": [
            {"id": 1, "start": 0, "end": 1, "name": "ST"},
            {"id": 2, "start": 1, "end": 4, "name": "Cust_Area"},
            {"id": 3, "start": 4, "end": 5, "name": "SecCode"},
            {"id": 4, "start": 6, "end": 10, "name": "Heliport_Ident"},
            {"id": 5, "start": 10, "end": 12, "name": "ICAOCode"},
            {"id": 6, "start": 12, "end": 13, "name": "SubCode"},
            {"id": 7, "start": 13, "end": 19, "name": "ProcIdent"},
            {"id": 8, "start": 19, "end": 20, "name": "RouteType"},
            {"id": 9, "start": 20, "end": 25, "name": "TransIdent"},
            {"id": 10, "start": 26, "end": 29, "name": "SeqNbr"},
            {"id": 11, "start": 29, "end": 34, "name": "FixIdent"},
            {"id": 12, "start": 34, "end": 36, "name": "ICAOCode2"},
            {"id": 13, "start": 36, "end": 37, "name": "SecCode2"},
            {"id": 14, "start": 37, "end": 38, "name": "SubCode2"},
            {"id": 15, "start": 38, "end": 39, "name": "ContRecordNumber"},
            {"id": 16, "start": 39, "end": 43, "name": "DescCode"},
            {"id": 17, "start": 43, "end": 44, "name": "TurnDir"},
            {"id": 18, "start": 44, "end": 47, "name": "RNP"},
            {"id": 19, "start": 47, "end": 49, "name": "PathTerminator"},
            {"id": 20, "start": 49, "end": 50, "name": "TurnDirValid"},
            {"id": 21, "start": 50, "end": 54, "name": "RecdNavaid"},
            {"id": 22, "start": 54, "end": 56, "name": "ICAOCode3"},
            {"id": 23, "start": 56, "end": 62, "name": "ArcRadius"},
            {"id": 24, "start": 62, "end": 66, "name": "Theta"},
            {"id": 25, "start": 66, "end": 70, "name": "Rho"},
            {"id": 26, "start": 70, "end": 74, "name": "MagCrs"},
            {"id": 27, "start": 74, "end": 78, "name": "RtHoldDistTime"},
            {"id": 28, "start": 78, "end": 79, "name": "SecCode3"},
            {"id": 29, "start": 79, "end": 80, "name": "SubCode3"},
            {"id": 30, "start": 82, "end": 83, "name": "AltDesc"},
            {"id": 31, "start": 83, "end": 84, "name": "ATC"},
            {"id": 32, "start": 84, "end": 89, "name": "Altitude1"},
            {"id": 33, "start": 89, "end": 94, "name": "Altitude2"},
            {"id": 34, "start": 94, "end": 99, "name": "TransAltitude"},
            {"id": 35, "start": 99, "end": 102, "name": "SpeedLimit"},
            {"id": 36, "start": 102, "end": 106, "name": "VertAngle"},
            {"id": 37, "start": 106, "end": 111, "name": "CenterFix"},
            {"id": 38, "start": 111, "end": 112, "name": "MultiCode"},
            {"id": 39, "start": 112, "end": 114, "name": "ICAOCode4"},
            {"id": 40, "start": 114, "end": 115, "name": "SecCode4"},
            {"id": 41, "start": 115, "end": 116, "name": "SubCode4"},
            {"id": 42, "start": 116, "end": 117, "name": "GNSS_FMSInd"},
            {"id": 43, "start": 117, "end": 118, "name": "SpeedLimitInd"},
            {"id": 44, "start": 118, "end": 119, "name": "RouteQual1"},
            {"id": 45, "start": 119, "end": 120, "name": "RouteQual2"},
            {"id": 46, "start": 123, "end": 128, "name": "FileRecordNumber"},
            {"id": 47, "start": 128, "end": 132, "name": "Cycle"},
        ],
    },
    {
        "name": "heli_approach_cont",
        "section_code": "H",
        "subsection_code": "F",
        "section_pos": 4,
        "subsection_pos": 12,
        "cont_rec_pos": 38,
        "cont_rec_vals": [2],
        "columns": [
            {"id": 1, "start": 0, "end": 1, "name": "ST"},
            {"id": 2, "start": 1, "end": 4, "name": "Cust_Area"},
            {"id": 3, "start": 4, "end": 5, "name": "SecCode"},
            {"id": 4, "start": 6, "end": 10, "name": "Heliport_Ident"},
            {"id": 5, "start": 10, "end": 12, "name": "ICAOCode"},
            {"id": 6, "start": 12, "end": 13, "name": "SubCode"},
            {"id": 7, "start": 13, "end": 19, "name": "ProcIdent"},
            {"id": 8, "start": 19, "end": 20, "name": "RouteType"},
            {"id": 9, "start": 20, "end": 25, "name": "TransIdent"},
            {"id": 10, "start": 26, "end": 29, "name": "SeqNbr"},
            {"id": 11, "start": 29, "end": 34, "name": "FixIdent"},
            {"id": 12, "start": 34, "end": 36, "name": "ICAOCode2"},
            {"id": 13, "start": 36, "end": 37, "name": "SecCode2"},
            {"id": 14, "start": 37, "end": 38, "name": "SubCode2"},
            {"id": 15, "start": 38, "end": 39, "name": "ContRecordNumber"},
            {"id": 16, "start": 39, "end": 40, "name": "Appl_Type"},
            {"id": 17, "start": 40, "end": 41, "name": "FAS_Block"},
            {"id": 18, "start": 41, "end": 51, "name": "FAS_Block_LOS_Name"},
            {"id": 19, "start": 51, "end": 52, "name": "LNAV_VNAV"},
            {"id": 20, "start": 52, "end": 62, "name": "LNAV_VNAV_LOS_Name"},
            {"id": 21, "start": 62, "end": 63, "name": "LNAV"},
            {"id": 22, "start": 63, "end": 73, "name": "LNAV_LOS_Name"},
            {"id": 23, "start": 118, "end": 119, "name": "Route_Qual1"},
            {"id": 24, "start": 119, "end": 120, "name": "Route_Qual2"},
            {"id": 25, "start": 123, "end": 128, "name": "FileRecordNumber"},
            {"id": 26, "start": 128, "end": 132, "name": "Cycle"},
        ],
    },
    {
        "name": "vhf_navaid",
        "section_code": "D",
        "subsection_code": " ",
        "section_pos": 4,
        "subsection_pos": 5,
        "cont_rec_pos": 21,
        "cont_rec_vals": [0, 1],
        "columns": [
            {"id": 1, "start": 0, "end": 1, "name": "ST"},
            {"id": 2, "start": 1, "end": 4, "name": "Cust_Area"},
            {"id": 3, "start": 4, "end": 5, "name": "SecCode"},
            {"id": 4, "start": 5, "end": 6, "name": "Subsection_Code"},
            {"id": 5, "start": 6, "end": 10, "name": "Airport_Identifier"},
            {"id": 6, "start": 10, "end": 12, "name": "ICAOCode"},
            {"id": 7, "start": 13, "end": 17, "name": "VOR_Identifier"},
            {"id": 8, "start": 19, "end": 21, "name": "ICAO_Code"},
            {"id": 9, "start": 21, "end": 22, "name": "Cont_Rec_Number"},
            {"id": 10, "start": 22, "end": 27, "name": "VOR_Frequency"},
            {"id": 11, "start": 27, "end": 32, "name": "NAVAID_Class"},
            {"id": 12, "start": 32, "end": 41, "name": "VOR_Latitude"},
            {"id": 13, "start": 41, "end": 51, "name": "VOR_Longitude"},
            {"id": 14, "start": 51, "end": 55, "name": "DME_Ident"},
            {"id": 15, "start": 55, "end": 64, "name": "DME_Latitude"},
            {"id": 16, "start": 64, "end": 74, "name": "DME_Longitude"},
            {"id": 17, "start": 74, "end": 79, "name": "Station_Declination"},
            {"id": 18, "start": 79, "end": 84, "name": "DME_Elevation"},
            {"id": 19, "start": 84, "end": 85, "name": "FOM"},
            {"id": 20, "start": 85, "end": 87, "name": "ILS_DME_Bias"},
            {"id": 21, "start": 87, "end": 90, "name": "Frequency_Protection"},
            {"id": 22, "start": 90, "end": 93, "name": "Datum_Code"},
            {"id": 23, "start": 93, "end": 123, "name": "VOR_Name"},
            {"id": 24, "start": 123, "end": 128, "name": "FileRecordNumber"},
            {"id": 25, "start": 128, "end": 132, "name": "Cycle"},
        ],
    },
    {
        "name": "enroute_airways",
        "section_code": "E",
        "subsection_code": "R",
        "section_pos": 4,
        "subsection_pos": 5,
        "cont_rec_pos": 38,
        "cont_rec_vals": [0, 1],
        "columns": [
            {"id": 1, "start": 0, "end": 1, "name": "ST"},
            {"id": 2, "start": 1, "end": 4, "name": "Cust_Area"},
            {"id": 3, "start": 4, "end": 5, "name": "SecCode"},
            {"id": 4, "start": 5, "end": 6, "name": "Subsection_Code"},
            {"id": 5, "start": 13, "end": 18, "name": "Route_Identifier"},
            {"id": 6, "start": 18, "end": 19, "name": "Sixth_Character"},
            {"id": 7, "start": 25, "end": 29, "name": "Sequence_Number"},
            {"id": 8, "start": 29, "end": 34, "name": "Fix_Identifier"},
            {"id": 9, "start": 34, "end": 36, "name": "ICAO_Code"},
            {"id": 10, "start": 36, "end": 37, "name": "Section_Code2"},
            {"id": 11, "start": 37, "end": 38, "name": "Subsection_Code2"},
            {"id": 12, "start": 38, "end": 39, "name": "Cont_Rec_Number"},
            {"id": 13, "start": 39, "end": 43, "name": "Wpt_Desc_Code"},
            {"id": 14, "start": 43, "end": 44, "name": "Boundary_Code"},
            {"id": 15, "start": 44, "end": 45, "name": "Route_Type"},
            {"id": 16, "start": 45, "end": 46, "name": "Level"},
            {"id": 17, "start": 46, "end": 47, "name": "Direction_Restriction"},
            {"id": 18, "start": 47, "end": 49, "name": "Cruise_Table_Indicator"},
            {"id": 19, "start": 49, "end": 50, "name": "EU_Indicator"},
            {"id": 20, "start": 50, "end": 54, "name": "Recommended_NAVAID"},
            {"id": 21, "start": 54, "end": 56, "name": "ICAO_Code2"},
            {"id": 22, "start": 56, "end": 59, "name": "RNP"},
            {"id": 23, "start": 62, "end": 66, "name": "Theta"},
            {"id": 24, "start": 66, "end": 70, "name": "Rho"},
            {"id": 25, "start": 70, "end": 74, "name": "Outbound_Mag_Course"},
            {"id": 26, "start": 74, "end": 78, "name": "Route_Distance_From"},
            {"id": 27, "start": 78, "end": 82, "name": "Inbound_Mag_Course"},
            {"id": 28, "start": 83, "end": 88, "name": "Min_Altitude1"},
            {"id": 29, "start": 88, "end": 93, "name": "Min_Altitude2"},
            {"id": 30, "start": 93, "end": 98, "name": "Max_Altitude"},
            {"id": 31, "start": 123, "end": 128, "name": "FileRecordNumber"},
            {"id": 32, "start": 128, "end": 132, "name": "Cycle"},
        ],
    },
    {
        "name": "ndb_navaid",
        "section_code": "D",
        "subsection_code": "B",
        "section_pos": 4,
        "subsection_pos": 5,
        "cont_rec_pos": 21,
        "cont_rec_vals": [0, 1],
        "columns": [
            {"id": 1, "start": 0, "end": 1, "name": "ST"},
            {"id": 2, "start": 1, "end": 4, "name": "Cust_Area"},
            {"id": 3, "start": 4, "end": 5, "name": "SecCode"},
            {"id": 4, "start": 5, "end": 6, "name": "Subsection_Code"},
            {"id": 5, "start": 6, "end": 10, "name": "Airport_Identifier"},
            {"id": 6, "start": 10, "end": 12, "name": "ICAOCode"},
            {"id": 7, "start": 13, "end": 17, "name": "NDB_Identifier"},
            {"id": 8, "start": 19, "end": 21, "name": "ICAO_Code"},
            {"id": 9, "start": 21, "end": 22, "name": "Cont_Rec_Number"},
            {"id": 10, "start": 22, "end": 27, "name": "NDB_Frequency"},
            {"id": 11, "start": 27, "end": 32, "name": "NDB_Class"},
            {"id": 12, "start": 32, "end": 41, "name": "NDB_Latitude"},
            {"id": 13, "start": 41, "end": 51, "name": "NDB_Longitude"},
            {"id": 14, "start": 74, "end": 79, "name": "Magnetic_Variation"},
            {"id": 15, "start": 90, "end": 93, "name": "Datum_Code"},
            {"id": 16, "start": 93, "end": 123, "name": "NDB_Name"},
            {"id": 17, "start": 123, "end": 128, "name": "FileRecordNumber"},
            {"id": 18, "start": 128, "end": 132, "name": "Cycle"},
        ],
    },
    {
        "name": "terminal_navaid",
        "section_code": "P",
        "subsection_code": "N",
        "section_pos": 4,
        "subsection_pos": 5,
        "cont_rec_pos": 21,
        "cont_rec_vals": [0, 1],
        "columns": [
            {"id": 1, "start": 0, "end": 1, "name": "ST"},
            {"id": 2, "start": 1, "end": 4, "name": "Cust_Area"},
            {"id": 3, "start": 4, "end": 5, "name": "SecCode"},
            {"id": 4, "start": 5, "end": 6, "name": "Subsection_Code"},
            {"id": 5, "start": 6, "end": 10, "name": "Airport_Identifier"},
            {"id": 6, "start": 10, "end": 12, "name": "ICAOCode"},
            {"id": 7, "start": 13, "end": 17, "name": "NDB_Identifier"},
            {"id": 8, "start": 19, "end": 21, "name": "ICAO_Code"},
            {"id": 9, "start": 21, "end": 22, "name": "Cont_Rec_Number"},
            {"id": 10, "start": 22, "end": 27, "name": "NDB_Frequency"},
            {"id": 11, "start": 27, "end": 32, "name": "NDB_Class"},
            {"id": 12, "start": 32, "end": 41, "name": "NDB_Latitude"},
            {"id": 13, "start": 41, "end": 51, "name": "NDB_Longitude"},
            {"id": 14, "start": 74, "end": 79, "name": "Magnetic_Variation"},
            {"id": 15, "start": 90, "end": 93, "name": "Datum_Code"},
            {"id": 16, "start": 93, "end": 123, "name": "NDB_Name"},
            {"id": 17, "start": 123, "end": 128, "name": "FileRecordNumber"},
            {"id": 18, "start": 128, "end": 132, "name": "Cycle"},
        ],
    },
    {
        "name": "localizer",
        "section_code": "P",
        "subsection_code": "I",
        "section_pos": 4,
        "subsection_pos": 12,
        "cont_rec_pos": 21,
        "cont_rec_vals": [0, 1],
        "columns": [
            {"id": 1, "start": 0, "end": 1, "name": "ST"},
            {"id": 2, "start": 1, "end": 4, "name": "Cust_Area"},
            {"id": 3, "start": 4, "end": 5, "name": "SecCode"},
            {"id": 4, "start": 6, "end": 10, "name": "Airport_Identifier"},
            {"id": 5, "start": 12, "end": 13, "name": "Subsection_Code"},
            {"id": 6, "start": 13, "end": 17, "name": "Localizer_Identifier"},
            {"id": 7, "start": 17, "end": 18, "name": "ILS_Category"},
            {"id": 8, "start": 21, "end": 22, "name": "Cont_Rec_Number"},
            {"id": 9, "start": 22, "end": 27, "name": "Localizer_Frequency"},
            {"id": 10, "start": 27, "end": 32, "name": "Runway_Identifier"},
            {"id": 11, "start": 32, "end": 41, "name": "Localizer_Latitude"},
            {"id": 12, "start": 41, "end": 51, "name": "Localizer_Longitude"},
            {"id": 13, "start": 51, "end": 55, "name": "Localizer_Bearing"},
            {"id": 14, "start": 55, "end": 64, "name": "Glide_Slope_Latitude"},
            {"id": 15, "start": 64, "end": 74, "name": "Glide_Slope_Longitude"},
            {"id": 16, "start": 74, "end": 78, "name": "Localizer_Position"},
            {"id": 17, "start": 78, "end": 79, "name": "Localizer_Position_Ref"},
            {"id": 18, "start": 79, "end": 83, "name": "Glide_Slope_Position"},
            {"id": 19, "start": 83, "end": 87, "name": "Localizer_Width"},
            {"id": 20, "start": 87, "end": 90, "name": "Glide_Slope_Angle"},
            {"id": 21, "start": 90, "end": 95, "name": "Station_Declination"},
            {"id": 22, "start": 95, "end": 97, "name": "GS_Threshold_Landing_Height"},
            {"id": 23, "start": 97, "end": 102, "name": "Glide_Slope_Elevation"},
            {"id": 24, "start": 123, "end": 128, "name": "FileRecordNumber"},
            {"id": 25, "start": 128, "end": 132, "name": "Cycle"},
        ],
    },
    {
        "name": "controlled_airspace",
        "section_code": "U",
        "subsection_code": "C",
        "section_pos": 4,
        "subsection_pos": 5,
        "cont_rec_pos": 24,
        "cont_rec_vals": [0, 1],
        "columns": [
            {"id": 1, "start": 0, "end": 1, "name": "ST"},
            {"id": 2, "start": 1, "end": 4, "name": "Cust_Area"},
            {"id": 3, "start": 4, "end": 5, "name": "Section_Code"},
            {"id": 4, "start": 5, "end": 6, "name": "Subsection_Code"},
            {"id": 5, "start": 6, "end": 8, "name": "ICAO_Code"},
            {"id": 6, "start": 8, "end": 9, "name": "Airspace_Type"},
            {"id": 7, "start": 9, "end": 14, "name": "Airspace_Center"},
            {"id": 8, "start": 14, "end": 15, "name": "Section_Code2"},
            {"id": 9, "start": 15, "end": 16, "name": "Subsection_Code2"},
            {"id": 10, "start": 16, "end": 17, "name": "Airspace_Class"},
            {"id": 11, "start": 19, "end": 20, "name": "Multi_Code"},
            {"id": 12, "start": 20, "end": 24, "name": "Sequence_Nbr"},
            {"id": 13, "start": 24, "end": 25, "name": "Cont_Rec_Number"},
            {"id": 14, "start": 25, "end": 26, "name": "Level"},
            {"id": 15, "start": 26, "end": 27, "name": "Time_Code"},
            {"id": 16, "start": 27, "end": 28, "name": "NOTAM"},
            {"id": 17, "start": 30, "end": 32, "name": "Boundary_Via"},
            {"id": 18, "start": 32, "end": 41, "name": "Latitude"},
            {"id": 19, "start": 41, "end": 51, "name": "Longitude"},
            {"id": 20, "start": 51, "end": 60, "name": "Arc_Origin_Lat"},
            {"id": 21, "start": 60, "end": 70, "name": "Arc_Origin_Lon"},
            {"id": 22, "start": 70, "end": 74, "name": "Arc_Distance"},
            {"id": 23, "start": 74, "end": 78, "name": "Arc_Bearing"},
            {"id": 24, "start": 78, "end": 81, "name": "RNP"},
            {"id": 25, "start": 81, "end": 86, "name": "Lower_Limit"},
            {"id": 26, "start": 86, "end": 87, "name": "LL_Unit_Ind"},
            {"id": 27, "start": 87, "end": 92, "name": "Upper_Limit"},
            {"id": 28, "start": 92, "end": 93, "name": "UL_Unit_Ind"},
            {"id": 29, "start": 93, "end": 123, "name": "Airspace_Name"},
            {"id": 30, "start": 123, "end": 128, "name": "FileRecordNumber"},
            {"id": 31, "start": 128, "end": 132, "name": "Cycle"},
        ],
    },
    {
        "name": "msa",
        "section_code": "P",
        "subsection_code": "S",
        "section_pos": 4,
        "subsection_pos": 12,
        "cont_rec_pos": 38,
        "cont_rec_vals": [0, 1],
        "columns": [
            {"id": 1, "start": 0, "end": 1, "name": "ST"},
            {"id": 2, "start": 1, "end": 4, "name": "Cust_Area"},
            {"id": 3, "start": 4, "end": 5, "name": "Section_Code"},
            {"id": 4, "start": 6, "end": 10, "name": "Airport_Ident"},  
            {"id": 5, "start": 10, "end": 12, "name": "ICAO_Code"},
            {"id": 6, "start": 12, "end": 13, "name": "Subsection_Code"},
            {"id": 7, "start": 13, "end": 18, "name": "MSA_Center"},
            {"id": 8, "start": 18, "end": 20, "name": "ICAO_Code2"},
            {"id": 9, "start": 20, "end": 21, "name": "Section_Code2"},
            {"id": 10, "start": 21, "end": 22, "name": "Subsection_Code2"},
            {"id": 11, "start": 22, "end": 23, "name": "Multi_Code"},
            {"id": 12, "start": 38, "end": 39, "name": "Cont_Rec_Number"},
            {"id": 13, "start": 42, "end": 48, "name": "Sector_Bearing1"},
            {"id": 14, "start": 48, "end": 51, "name": "Sector_Altitude1"},
            {"id": 15, "start": 51, "end": 53, "name": "Sector_Radial1"},
            {"id": 16, "start": 53, "end": 59, "name": "Sector_Bearing2"},
            {"id": 17, "start": 59, "end": 62, "name": "Sector_Altitude2"},
            {"id": 18, "start": 62, "end": 64, "name": "Sector_Radial2"},
            {"id": 19, "start": 64, "end": 70, "name": "Sector_Bearing3"},
            {"id": 20, "start": 70, "end": 73, "name": "Sector_Altitude3"},
            {"id": 21, "start": 73, "end": 75, "name": "Sector_Radial3"},
            {"id": 22, "start": 75, "end": 81, "name": "Sector_Bearing4"},
            {"id": 23, "start": 81, "end": 84, "name": "Sector_Altitude4"},
            {"id": 24, "start": 84, "end": 86, "name": "Sector_Radial4"},
            {"id": 25, "start": 86, "end": 92, "name": "Sector_Bearing5"},
            {"id": 26, "start": 92, "end": 95, "name": "Sector_Altitude5"},
            {"id": 27, "start": 95, "end": 97, "name": "Sector_Radial5"},
            {"id": 28, "start": 97, "end": 103, "name": "Sector_Bearing6"},
            {"id": 29, "start": 103, "end": 106, "name": "Sector_Altitude6"},
            {"id": 30, "start": 106, "end": 108, "name": "Sector_Radial6"},
            {"id": 31, "start": 108, "end": 114, "name": "Sector_Bearing7"},
            {"id": 32, "start": 114, "end": 117, "name": "Sector_Altitude7"},
            {"id": 33, "start": 117, "end": 119, "name": "Sector_Radial7"},
            {"id": 34, "start": 119, "end": 120, "name": "Mag_Ind"},
            {"id": 35, "start": 123, "end": 128, "name": "FileRecordNumber"},
            {"id": 36, "start": 128, "end": 132, "name": "Cycle"},
        ],
    },
    {
        "name": "heli_msa",
        "section_code": "H",
        "subsection_code": "S",
        "section_pos": 4,
        "subsection_pos": 12,
        "cont_rec_pos": 38,
        "cont_rec_vals": [0, 1],
        "columns": [
            {"id": 1, "start": 0, "end": 1, "name": "ST"},
            {"id": 2, "start": 1, "end": 4, "name": "Cust_Area"},
            {"id": 3, "start": 4, "end": 5, "name": "Section_Code"},
            {"id": 4, "start": 6, "end": 10, "name": "Heliport_Ident"},  
            {"id": 5, "start": 10, "end": 12, "name": "ICAO_Code"},
            {"id": 6, "start": 12, "end": 13, "name": "Subsection_Code"},
            {"id": 7, "start": 13, "end": 18, "name": "MSA_Center"},
            {"id": 8, "start": 18, "end": 20, "name": "ICAO_Code2"},
            {"id": 9, "start": 20, "end": 21, "name": "Section_Code2"},
            {"id": 10, "start": 21, "end": 22, "name": "Subsection_Code2"},
            {"id": 11, "start": 22, "end": 23, "name": "Multi_Code"},
            {"id": 12, "start": 38, "end": 39, "name": "Cont_Rec_Number"},
            {"id": 13, "start": 42, "end": 48, "name": "Sector_Bearing1"},
            {"id": 14, "start": 48, "end": 51, "name": "Sector_Altitude1"},
            {"id": 15, "start": 51, "end": 53, "name": "Sector_Radial1"},
            {"id": 16, "start": 53, "end": 59, "name": "Sector_Bearing2"},
            {"id": 17, "start": 59, "end": 62, "name": "Sector_Altitude2"},
            {"id": 18, "start": 62, "end": 64, "name": "Sector_Radial2"},
            {"id": 19, "start": 64, "end": 70, "name": "Sector_Bearing3"},
            {"id": 20, "start": 70, "end": 73, "name": "Sector_Altitude3"},
            {"id": 21, "start": 73, "end": 75, "name": "Sector_Radial3"},
            {"id": 22, "start": 75, "end": 81, "name": "Sector_Bearing4"},
            {"id": 23, "start": 81, "end": 84, "name": "Sector_Altitude4"},
            {"id": 24, "start": 84, "end": 86, "name": "Sector_Radial4"},
            {"id": 25, "start": 86, "end": 92, "name": "Sector_Bearing5"},
            {"id": 26, "start": 92, "end": 95, "name": "Sector_Altitude5"},
            {"id": 27, "start": 95, "end": 97, "name": "Sector_Radial5"},
            {"id": 28, "start": 97, "end": 103, "name": "Sector_Bearing6"},
            {"id": 29, "start": 103, "end": 106, "name": "Sector_Altitude6"},
            {"id": 30, "start": 106, "end": 108, "name": "Sector_Radial6"},
            {"id": 31, "start": 108, "end": 114, "name": "Sector_Bearing7"},
            {"id": 32, "start": 114, "end": 117, "name": "Sector_Altitude7"},
            {"id": 33, "start": 117, "end": 119, "name": "Sector_Radial7"},
            {"id": 34, "start": 119, "end": 120, "name": "Mag_Ind"},
            {"id": 35, "start": 123, "end": 128, "name": "FileRecordNumber"},
            {"id": 36, "start": 128, "end": 132, "name": "Cycle"},
        ],
    },
    {
        "name": "restrictive_airspace",
        "section_code": "U",
        "subsection_code": "R",
        "section_pos": 4,
        "subsection_pos": 5,
        "cont_rec_pos": 24,
        "cont_rec_vals": [0, 1],
        "columns": [
            {"id": 1, "start": 0, "end": 1, "name": "ST"},
            {"id": 2, "start": 1, "end": 4, "name": "Cust_Area"},
            {"id": 3, "start": 4, "end": 5, "name": "Section_Code"},
            {"id": 4, "start": 5, "end": 6, "name": "Subsection_Code"},
            {"id": 5, "start": 6, "end": 8, "name": "ICAO_Code"},
            {"id": 6, "start": 8, "end": 9, "name": "Restriction_Type"},
            {"id": 7, "start": 9, "end": 19, "name": "Designation"},
            {"id": 8, "start": 19, "end": 20, "name": "Multi_Code"},
            {"id": 9, "start": 20, "end": 24, "name": "Sequence_Nbr"},
            {"id": 10, "start": 24, "end": 25, "name": "Cont_Rec_Number"},
            {"id": 11, "start": 25, "end": 26, "name": "Level"},
            {"id": 12, "start": 26, "end": 27, "name": "Time_Code"},
            {"id": 13, "start": 27, "end": 28, "name": "NOTAM"},
            {"id": 14, "start": 30, "end": 32, "name": "Boundary_Via"},
            {"id": 15, "start": 32, "end": 41, "name": "Latitude"},
            {"id": 16, "start": 41, "end": 51, "name": "Longitude"},
            {"id": 17, "start": 51, "end": 60, "name": "Arc_Origin_Lat"},
            {"id": 18, "start": 60, "end": 70, "name": "Arc_Origin_Lon"},
            {"id": 19, "start": 70, "end": 74, "name": "Arc_Distance"},
            {"id": 20, "start": 74, "end": 78, "name": "Arc_Bearing"},
            {"id": 21, "start": 81, "end": 86, "name": "Lower_Limit"},
            {"id": 22, "start": 86, "end": 87, "name": "LL_Unit_Ind"},
            {"id": 23, "start": 87, "end": 92, "name": "Upper_Limit"},
            {"id": 24, "start": 92, "end": 93, "name": "UL_Unit_Ind"},
            {"id": 25, "start": 93, "end": 123, "name": "Restr_Airspace_Name"},
            {"id": 26, "start": 123, "end": 128, "name": "FileRecordNumber"},
            {"id": 27, "start": 128, "end": 132, "name": "Cycle"},
        ],
    },
]
